app:
  name: admin
server:
  http:
    addr: 0.0.0.0:8000
    timeout: 1s
  grpc:
    addr: 0.0.0.0:9000
    timeout: 1s
data:
  database:
    driver: mysql
    source: root:password@tcp(127.0.0.1:3306)/test
  redis:
    addr: 127.0.0.1:6379
task:
  broker: amqp://guest:guest@localhost:5672
  queue: tasks
  resultBackend: amqp://guest:guest@localhost:5672
  exchange: tasks
  exchangeType: direct